version: "3.9"

services:
  blog_api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: blog_api
    restart: unless-stopped
    depends_on:
      - mariadb
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/var/www
      - vendor-data:/var/www/vendor
    ports:
    - "8000:8000"
    networks:
      - app-network
    command: sh -c "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000"

  blog_app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: blog_app
    restart: unless-stopped
    depends_on:
      - blog_api
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend:/var/www
      - ./frontend/.output/public:/var/www/html
    depends_on:
      - blog_api
      - blog_app
    networks:
      - app-network

  mariadb:
    image: mariadb:10
    restart: unless-stopped
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cms_db
      MYSQL_USER: jakkrit
      MYSQL_PASSWORD: secret1234!
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mariadb-data:
  vendor-data:

networks:
  app-network:
